-- Add new enum values (use exact enum name from schema)
ALTER TYPE "GoogleSheetsOp" ADD VALUE IF NOT EXISTS 'UPDATE_ROW';
ALTER TYPE "GoogleSheetsOp" ADD VALUE IF NOT EXISTS 'UPDATE_ROWS_BY_QUERY';
ALTER TYPE "GoogleSheetsOp" ADD VALUE IF NOT EXISTS 'DELETE_ROW';
ALTER TYPE "GoogleSheetsOp" ADD VALUE IF NOT EXISTS 'GET_ROW_BY_NUMBER';
ALTER TYPE "GoogleSheetsOp" ADD VALUE IF NOT EXISTS 'SEARCH_ROWS';
ALTER TYPE "GoogleSheetsOp" ADD VALUE IF NOT EXISTS 'CLEAR_RANGE';
ALTER TYPE "GoogleSheetsOp" ADD VALUE IF NOT EXISTS 'CREATE_SHEET';
ALTER TYPE "GoogleSheetsOp" ADD VALUE IF NOT EXISTS 'GET_SHEET_INFO';

-- Add new columns (skip any that already exist)
ALTER TABLE "GoogleSheetsNode"
  ADD COLUMN IF NOT EXISTS "variableName" TEXT NOT NULL DEFAULT 'googleSheets';
ALTER TABLE "GoogleSheetsNode"
  ADD COLUMN IF NOT EXISTS "headerRow" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "GoogleSheetsNode"
  ADD COLUMN IF NOT EXISTS "rowNumber" TEXT NOT NULL DEFAULT '';
ALTER TABLE "GoogleSheetsNode"
  ADD COLUMN IF NOT EXISTS "rowValues" TEXT NOT NULL DEFAULT '';
ALTER TABLE "GoogleSheetsNode"
  ADD COLUMN IF NOT EXISTS "searchColumn" TEXT NOT NULL DEFAULT '';
ALTER TABLE "GoogleSheetsNode"
  ADD COLUMN IF NOT EXISTS "searchValue" TEXT NOT NULL DEFAULT '';
ALTER TABLE "GoogleSheetsNode"
  ADD COLUMN IF NOT EXISTS "clearRange" TEXT NOT NULL DEFAULT '';
ALTER TABLE "GoogleSheetsNode"
  ADD COLUMN IF NOT EXISTS "newSheetName" TEXT NOT NULL DEFAULT '';
ALTER TABLE "GoogleSheetsNode"
  ADD COLUMN IF NOT EXISTS "valueInputOption"
  TEXT NOT NULL DEFAULT 'USER_ENTERED';
ALTER TABLE "GoogleSheetsNode"
  ADD COLUMN IF NOT EXISTS "matchColumn" TEXT NOT NULL DEFAULT '';
ALTER TABLE "GoogleSheetsNode"
  ADD COLUMN IF NOT EXISTS "matchValue" TEXT NOT NULL DEFAULT '';
ALTER TABLE "GoogleSheetsNode"
  ADD COLUMN IF NOT EXISTS "updateValues" TEXT NOT NULL DEFAULT '';
ALTER TABLE "GoogleSheetsNode"
  ADD COLUMN IF NOT EXISTS "maxResults" INTEGER NOT NULL DEFAULT 100;
ALTER TABLE "GoogleSheetsNode"
  ADD COLUMN IF NOT EXISTS "includeEmptyRows"
  BOOLEAN NOT NULL DEFAULT false;
