import type { Metadata } from "next";
import { Callout } from "@/components/docs/callout";
import { CodeBlock } from "@/components/docs/code-block";
import { Breadcrumb, PrevNextLinks } from "@/components/docs/docs-shell";

export const metadata: Metadata = { title: "WhatsApp Trigger Node" };

export default function WhatsAppTriggerPage() {
  return (
    <>
      <Breadcrumb
        items={[
          { label: "Nodes", href: "/docs/nodes" },
          { label: "WhatsApp Trigger" },
        ]}
      />

      <h1 className="text-4xl font-bold tracking-tight">
        WhatsApp Trigger Node
      </h1>
      <p className="mt-3 text-lg text-muted-foreground">
        Start a workflow whenever a WhatsApp message arrives — text, image,
        audio, video, location, button reply, order, and more. The foundation
        for building WhatsApp order bots, support automation, and OTP flows.
      </p>

      {/* Prerequisites */}
      <h2 id="prerequisites" className="mt-12 text-2xl font-bold">
        Prerequisites
      </h2>
      <ul className="mt-3 list-inside list-disc space-y-2 text-foreground/80">
        <li>
          A Meta Business account with a WhatsApp Business API phone number
        </li>
        <li>
          A Meta App with the <strong>WhatsApp Business</strong> product added
        </li>
        <li>
          A permanent{" "}
          <strong>System User access token</strong> (not a temporary token)
        </li>
        <li>
          Meta App Review approval if you plan to message non-test users
        </li>
      </ul>

      <Callout type="info">
        For testing, you can use the sandbox numbers provided by Meta in the
        WhatsApp Business API setup wizard without going through App Review.
      </Callout>

      {/* Setup */}
      <h2 id="setup" className="mt-12 text-2xl font-bold">
        Setup
      </h2>
      <ol className="mt-3 list-inside list-decimal space-y-2 text-foreground/80">
        <li>
          Add a <strong>WhatsApp Trigger</strong> node to your workflow canvas
        </li>
        <li>
          Configure the <strong>Phone Number ID</strong> filter (leave blank to
          receive from all numbers)
        </li>
        <li>
          Select <strong>Message Types</strong> to listen to
        </li>
        <li>
          Toggle <strong>Ignore Own Messages</strong> to avoid loops
        </li>
        <li>
          Click <strong>Save</strong> — Nodebase generates a webhook URL and
          verify token
        </li>
        <li>
          Go to{" "}
          <strong>
            Meta Developer Portal → Your App → WhatsApp → Configuration →
            Webhooks
          </strong>
        </li>
        <li>
          Paste the webhook URL and the auto-generated verify token
        </li>
        <li>
          Subscribe to the <strong>messages</strong> field
        </li>
        <li>Click Verify and Save</li>
      </ol>

      <Callout type="tip">
        The verify token is a UUID auto-generated by Nodebase. You can find it
        in the trigger node&apos;s configuration panel — copy it exactly as
        shown.
      </Callout>

      {/* Configuration */}
      <h2 id="configuration" className="mt-12 text-2xl font-bold">
        Configuration
      </h2>
      <div className="mt-4 overflow-x-auto rounded-lg border border-border">
        <table className="w-full text-sm">
          <thead>
            <tr className="border-b border-border bg-muted/50">
              <th className="px-4 py-2.5 text-left font-semibold">Field</th>
              <th className="px-4 py-2.5 text-left font-semibold">
                Description
              </th>
            </tr>
          </thead>
          <tbody>
            {[
              [
                "Phone Number ID",
                "Filter events to a specific phone number ID. Leave blank to receive from all.",
              ],
              [
                "Message Types",
                "Which message types trigger the workflow: text, image, audio, video, document, location, contacts, sticker, reaction, interactive, button, order, system.",
              ],
              [
                "Ignore Own Messages",
                "Skip messages sent from your own phone number ID. Prevents trigger loops.",
              ],
            ].map(([field, desc], i) => (
              <tr key={field} className={i % 2 ? "bg-muted/30" : ""}>
                <td className="px-4 py-2.5 font-medium">{field}</td>
                <td className="px-4 py-2.5 text-muted-foreground">{desc}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {/* Supported Message Types */}
      <h2 id="message-types" className="mt-12 text-2xl font-bold">
        Supported Message Types
      </h2>
      <div className="mt-4 overflow-x-auto rounded-lg border border-border">
        <table className="w-full text-sm">
          <thead>
            <tr className="border-b border-border bg-muted/50">
              <th className="px-4 py-2.5 text-left font-semibold">Type</th>
              <th className="px-4 py-2.5 text-left font-semibold">
                Key Variables Available
              </th>
            </tr>
          </thead>
          <tbody>
            {[
              ["text", "{{whatsappTrigger.text}}"],
              [
                "image / audio / video / document",
                "{{whatsappTrigger.mediaId}}, {{whatsappTrigger.caption}}, {{whatsappTrigger.filename}}",
              ],
              [
                "location",
                "{{whatsappTrigger.latitude}}, {{whatsappTrigger.longitude}}, {{whatsappTrigger.locationName}}, {{whatsappTrigger.address}}",
              ],
              [
                "interactive (button_reply)",
                "{{whatsappTrigger.buttonId}}, {{whatsappTrigger.buttonTitle}}",
              ],
              [
                "interactive (list_reply)",
                "{{whatsappTrigger.listId}}, {{whatsappTrigger.listTitle}}",
              ],
              [
                "reaction",
                "{{whatsappTrigger.emoji}}, {{whatsappTrigger.reactedToMsgId}}",
              ],
              ["order", "{{whatsappTrigger.raw}} (full order object)"],
              [
                "status event",
                '{{whatsappTrigger.status}} — "sent" / "delivered" / "read" / "failed"',
              ],
            ].map(([type, vars], i) => (
              <tr key={type} className={i % 2 ? "bg-muted/30" : ""}>
                <td className="px-4 py-2.5 font-mono text-xs font-medium">
                  {type}
                </td>
                <td className="px-4 py-2.5 font-mono text-xs text-muted-foreground">
                  {vars}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {/* Output Variables */}
      <h2 id="output" className="mt-12 text-2xl font-bold">
        Output Variables
      </h2>
      <div className="mt-4 overflow-x-auto rounded-lg border border-border">
        <table className="w-full text-sm">
          <thead>
            <tr className="border-b border-border bg-muted/50">
              <th className="px-4 py-2.5 text-left font-semibold">Variable</th>
              <th className="px-4 py-2.5 text-left font-semibold">Type</th>
              <th className="px-4 py-2.5 text-left font-semibold">
                Description
              </th>
              <th className="px-4 py-2.5 text-left font-semibold">Example</th>
            </tr>
          </thead>
          <tbody>
            {[
              [
                "{{whatsappTrigger.from}}",
                "string",
                "Sender phone number with country code",
                '"919876543210"',
              ],
              [
                "{{whatsappTrigger.senderName}}",
                "string",
                "Sender display name",
                '"Rahul Sharma"',
              ],
              [
                "{{whatsappTrigger.type}}",
                "string",
                "Message type",
                '"text"',
              ],
              [
                "{{whatsappTrigger.text}}",
                "string",
                "Message body (text messages only)",
                '"Track my order"',
              ],
              [
                "{{whatsappTrigger.mediaId}}",
                "string",
                "Media ID for image/audio/video/doc",
                '"1234567890"',
              ],
              [
                "{{whatsappTrigger.caption}}",
                "string",
                "Media caption",
                '"Product photo"',
              ],
              [
                "{{whatsappTrigger.filename}}",
                "string",
                "Document filename",
                '"invoice.pdf"',
              ],
              [
                "{{whatsappTrigger.latitude}}",
                "string",
                "Location latitude",
                '"19.0760"',
              ],
              [
                "{{whatsappTrigger.longitude}}",
                "string",
                "Location longitude",
                '"72.8777"',
              ],
              [
                "{{whatsappTrigger.locationName}}",
                "string",
                "Place name",
                '"Bandra Station"',
              ],
              [
                "{{whatsappTrigger.address}}",
                "string",
                "Location address",
                '"Bandra West, Mumbai"',
              ],
              [
                "{{whatsappTrigger.buttonId}}",
                "string",
                "Button reply ID",
                '"track_order"',
              ],
              [
                "{{whatsappTrigger.buttonTitle}}",
                "string",
                "Button label clicked",
                '"Track Order"',
              ],
              [
                "{{whatsappTrigger.listId}}",
                "string",
                "List reply row ID",
                '"size_m"',
              ],
              [
                "{{whatsappTrigger.listTitle}}",
                "string",
                "List reply row title",
                '"Medium"',
              ],
              [
                "{{whatsappTrigger.emoji}}",
                "string",
                "Reaction emoji",
                '"❤️"',
              ],
              [
                "{{whatsappTrigger.reactedToMsgId}}",
                "string",
                "ID of message that was reacted to",
                '"wamid.abcd1234"',
              ],
              [
                "{{whatsappTrigger.messageId}}",
                "string",
                "Unique WhatsApp message ID",
                '"wamid.HBgNOTE..."',
              ],
              [
                "{{whatsappTrigger.timestamp}}",
                "string",
                "Unix timestamp of message",
                '"1712051400"',
              ],
              [
                "{{whatsappTrigger.phoneNumberId}}",
                "string",
                "Your phone number ID",
                '"107900725821067"',
              ],
              [
                "{{whatsappTrigger.eventType}}",
                "string",
                '"message" or "message_status"',
                '"message"',
              ],
              [
                "{{whatsappTrigger.status}}",
                "string",
                "Delivery status (status events only)",
                '"delivered"',
              ],
              [
                "{{whatsappTrigger.raw}}",
                "object",
                "Full raw webhook payload",
                "{ ... }",
              ],
            ].map(([variable, type, desc, example], i) => (
              <tr key={variable} className={i % 2 ? "bg-muted/30" : ""}>
                <td className="px-4 py-2.5">
                  <code className="rounded bg-muted px-1 py-0.5 font-mono text-xs text-orange">
                    {variable}
                  </code>
                </td>
                <td className="px-4 py-2.5 font-mono text-xs text-muted-foreground">
                  {type}
                </td>
                <td className="px-4 py-2.5 text-muted-foreground">{desc}</td>
                <td className="px-4 py-2.5 font-mono text-xs text-muted-foreground">
                  {example}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {/* Complete Workflow Examples */}
      <h2 id="examples" className="mt-12 text-2xl font-bold">
        Complete Workflow Examples
      </h2>

      <h3 id="example-order-bot" className="mt-8 text-xl font-semibold">
        WhatsApp Order Tracking Bot
      </h3>
      <p className="mt-2 text-foreground/80">
        <strong>Use case:</strong> Customer types an order ID on WhatsApp and
        receives live tracking status.
      </p>
      <CodeBlock
        language="text"
        title="Workflow"
        code={`WhatsApp Trigger (messageTypes: text)
→ Shiprocket — Track Shipment
    awbCode: {{whatsappTrigger.text}}
→ WhatsApp — Send Message
    to:      {{whatsappTrigger.from}}
    message: "Order status: {{shiprocket.current_status}}
              Last update: {{shiprocket.tracking_data.etd}}"`}
      />

      <h3 id="example-image-support" className="mt-8 text-xl font-semibold">
        Customer Support — Image Complaint
      </h3>
      <p className="mt-2 text-foreground/80">
        <strong>Use case:</strong> When a customer sends a product image
        (e.g. damaged item), log it and notify the support team.
      </p>
      <CodeBlock
        language="text"
        title="Workflow"
        code={`WhatsApp Trigger (messageTypes: image)
→ Google Sheets — Append Row
    spreadsheetId: {{env.COMPLAINTS_SHEET_ID}}
    values:
      - from:    {{whatsappTrigger.from}}
      - name:    {{whatsappTrigger.senderName}}
      - mediaId: {{whatsappTrigger.mediaId}}
      - caption: {{whatsappTrigger.caption}}
      - time:    {{whatsappTrigger.timestamp}}
→ Slack — Send Message
    channel: #support
    text:    "New complaint from {{whatsappTrigger.senderName}} ({{whatsappTrigger.from}}):
              {{whatsappTrigger.caption}}"
→ WhatsApp — Send Message
    to:      {{whatsappTrigger.from}}
    message: "Hi {{whatsappTrigger.senderName}}, we've received your complaint
              and will respond within 24 hours."`}
      />

      {/* Common Issues */}
      <h2 id="issues" className="mt-12 text-2xl font-bold">
        Common Issues &amp; Solutions
      </h2>
      <div className="mt-4 overflow-x-auto rounded-lg border border-border">
        <table className="w-full text-sm">
          <thead>
            <tr className="border-b border-border bg-muted/50">
              <th className="px-4 py-2.5 text-left font-semibold">Issue</th>
              <th className="px-4 py-2.5 text-left font-semibold">Cause</th>
              <th className="px-4 py-2.5 text-left font-semibold">Solution</th>
            </tr>
          </thead>
          <tbody>
            {[
              [
                "Webhook verification fails",
                "Wrong verify token entered in Meta portal",
                "Copy the verify token exactly from the Nodebase node panel — no extra spaces",
              ],
              [
                "No events received",
                "messages field not subscribed in Meta portal",
                "Go to App → WhatsApp → Configuration → Webhooks and subscribe to messages",
              ],
              [
                "{{whatsappTrigger.text}} is empty",
                "Message is not a text type",
                "Check {{whatsappTrigger.type}} first with If/Else before reading .text",
              ],
              [
                "Trigger fires for own sent messages",
                "Ignore Own Messages is off",
                "Enable Ignore Own Messages in the node configuration",
              ],
            ].map(([issue, cause, solution], i) => (
              <tr key={issue} className={i % 2 ? "bg-muted/30" : ""}>
                <td className="px-4 py-2.5 font-medium">{issue}</td>
                <td className="px-4 py-2.5 text-muted-foreground">{cause}</td>
                <td className="px-4 py-2.5 text-muted-foreground">
                  {solution}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {/* Related Nodes */}
      <h2 id="related" className="mt-12 text-2xl font-bold">
        Related Nodes
      </h2>
      <ul className="mt-3 list-inside list-disc space-y-1 text-foreground/80">
        <li>
          <a href="/docs/nodes/whatsapp" className="text-orange underline">
            WhatsApp
          </a>{" "}
          — send replies, templates, and media back to the user
        </li>
        <li>
          <a href="/docs/nodes/if-else" className="text-orange underline">
            If / Else
          </a>{" "}
          — branch on message type or content
        </li>
        <li>
          <a href="/docs/nodes/shiprocket" className="text-orange underline">
            Shiprocket
          </a>{" "}
          — look up order tracking from the message text
        </li>
        <li>
          <a href="/docs/nodes/msg91" className="text-orange underline">
            MSG91
          </a>{" "}
          — send OTP or SMS in addition to WhatsApp
        </li>
        <li>
          <a href="/docs/nodes/ai" className="text-orange underline">
            AI Nodes
          </a>{" "}
          — build intelligent chatbot responses using the message text
        </li>
      </ul>

      <PrevNextLinks />
    </>
  );
}
