-- CreateEnum
CREATE TYPE "GmailOperation" AS ENUM ('SEND', 'REPLY', 'FORWARD', 'GET_MESSAGE', 'LIST_MESSAGES', 'SEARCH_MESSAGES', 'ADD_LABEL', 'REMOVE_LABEL', 'MARK_READ', 'MARK_UNREAD', 'MOVE_TO_TRASH', 'CREATE_DRAFT');

-- Add operation and variableName columns
ALTER TABLE "GmailNode" ADD COLUMN IF NOT EXISTS "operation" "GmailOperation" NOT NULL DEFAULT 'SEND';
ALTER TABLE "GmailNode" ADD COLUMN IF NOT EXISTS "variableName" TEXT NOT NULL DEFAULT 'gmail';

-- Add new fields to GmailNode
ALTER TABLE "GmailNode" ADD COLUMN IF NOT EXISTS "cc" TEXT NOT NULL DEFAULT '';
ALTER TABLE "GmailNode" ADD COLUMN IF NOT EXISTS "bcc" TEXT NOT NULL DEFAULT '';
ALTER TABLE "GmailNode" ADD COLUMN IF NOT EXISTS "replyTo" TEXT NOT NULL DEFAULT '';
ALTER TABLE "GmailNode" ADD COLUMN IF NOT EXISTS "messageId" TEXT NOT NULL DEFAULT '';
ALTER TABLE "GmailNode" ADD COLUMN IF NOT EXISTS "threadId" TEXT NOT NULL DEFAULT '';
ALTER TABLE "GmailNode" ADD COLUMN IF NOT EXISTS "searchQuery" TEXT NOT NULL DEFAULT '';
ALTER TABLE "GmailNode" ADD COLUMN IF NOT EXISTS "maxResults" INTEGER NOT NULL DEFAULT 10;
ALTER TABLE "GmailNode" ADD COLUMN IF NOT EXISTS "labelIds" TEXT NOT NULL DEFAULT '';
ALTER TABLE "GmailNode" ADD COLUMN IF NOT EXISTS "includeBody" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "GmailNode" ADD COLUMN IF NOT EXISTS "includeHeaders" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "GmailNode" ADD COLUMN IF NOT EXISTS "pageToken" TEXT NOT NULL DEFAULT '';
ALTER TABLE "GmailNode" ADD COLUMN IF NOT EXISTS "attachmentData" TEXT NOT NULL DEFAULT '';
ALTER TABLE "GmailNode" ADD COLUMN IF NOT EXISTS "attachmentName" TEXT NOT NULL DEFAULT '';
ALTER TABLE "GmailNode" ADD COLUMN IF NOT EXISTS "attachmentMime"
  TEXT NOT NULL DEFAULT 'application/octet-stream';
