-- Add new enum values to SlackOperation
ALTER TYPE "SlackOperation" ADD VALUE IF NOT EXISTS 'MESSAGE_SCHEDULE';
ALTER TYPE "SlackOperation" ADD VALUE IF NOT EXISTS 'CHANNEL_GET';
ALTER TYPE "SlackOperation" ADD VALUE IF NOT EXISTS 'USER_GET';
ALTER TYPE "SlackOperation" ADD VALUE IF NOT EXISTS 'USER_GET_BY_EMAIL';
ALTER TYPE "SlackOperation" ADD VALUE IF NOT EXISTS 'USER_SET_STATUS';
ALTER TYPE "SlackOperation" ADD VALUE IF NOT EXISTS 'FILE_GET';

-- Add new columns to SlackNode
ALTER TABLE "SlackNode" ADD COLUMN IF NOT EXISTS "blockKit" TEXT NOT NULL DEFAULT '';
ALTER TABLE "SlackNode" ADD COLUMN IF NOT EXISTS "botName" TEXT NOT NULL DEFAULT '';
ALTER TABLE "SlackNode" ADD COLUMN IF NOT EXISTS "iconEmoji" TEXT NOT NULL DEFAULT '';
ALTER TABLE "SlackNode" ADD COLUMN IF NOT EXISTS "unfurlLinks" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "SlackNode" ADD COLUMN IF NOT EXISTS "channelTypes" TEXT NOT NULL DEFAULT 'public_channel,private_channel';
ALTER TABLE "SlackNode" ADD COLUMN IF NOT EXISTS "limit" INTEGER NOT NULL DEFAULT 100;
ALTER TABLE "SlackNode" ADD COLUMN IF NOT EXISTS "excludeArchived" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "SlackNode" ADD COLUMN IF NOT EXISTS "isPrivate" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "SlackNode" ADD COLUMN IF NOT EXISTS "filename" TEXT NOT NULL DEFAULT '';
ALTER TABLE "SlackNode" ADD COLUMN IF NOT EXISTS "fileType" TEXT NOT NULL DEFAULT '';
ALTER TABLE "SlackNode" ADD COLUMN IF NOT EXISTS "title" TEXT NOT NULL DEFAULT '';
ALTER TABLE "SlackNode" ADD COLUMN IF NOT EXISTS "initialComment" TEXT NOT NULL DEFAULT '';
ALTER TABLE "SlackNode" ADD COLUMN IF NOT EXISTS "email" TEXT NOT NULL DEFAULT '';
ALTER TABLE "SlackNode" ADD COLUMN IF NOT EXISTS "statusText" TEXT NOT NULL DEFAULT '';
ALTER TABLE "SlackNode" ADD COLUMN IF NOT EXISTS "statusEmoji" TEXT NOT NULL DEFAULT '';
ALTER TABLE "SlackNode" ADD COLUMN IF NOT EXISTS "statusExpiration" TEXT NOT NULL DEFAULT '';
ALTER TABLE "SlackNode" ADD COLUMN IF NOT EXISTS "sendAt" TEXT NOT NULL DEFAULT '';
ALTER TABLE "SlackNode" ADD COLUMN IF NOT EXISTS "content" TEXT NOT NULL DEFAULT '';
ALTER TABLE "SlackNode" ADD COLUMN IF NOT EXISTS "fileId" TEXT NOT NULL DEFAULT '';
