-- AlterTable
ALTER TABLE "CodeNode" ADD COLUMN IF NOT EXISTS "language"       TEXT    NOT NULL DEFAULT 'javascript';
ALTER TABLE "CodeNode" ADD COLUMN IF NOT EXISTS "outputMode"     TEXT    NOT NULL DEFAULT 'append';
ALTER TABLE "CodeNode" ADD COLUMN IF NOT EXISTS "timeout"        INTEGER NOT NULL DEFAULT 5000;
ALTER TABLE "CodeNode" ADD COLUMN IF NOT EXISTS "continueOnFail" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "CodeNode" ADD COLUMN IF NOT EXISTS "allowedDomains" TEXT    NOT NULL DEFAULT '';
